apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "Devsecops With Aws"
    - name: trainer
      value: "Sivakunar Reddy"
    - name: duration
      value: "120hrs"
