apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: dotfile-secret
          key: username
    - name: PASSWORD
      valueFrom:
        ecretKeyRef:
          name: dotfile-secret
          key: password
