apiVersion: v1
kind: Service
metadata:
  name: nginx-nordeport
spec:
  type: NodePort
  selector:  # labels are used in as selectors
    project: expense-project
    component: backend
    environment: dev  
    version: "1.0.0"
    demo: nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: backend-nordport
  labels:
    project: expense-project
    component: backend
    environment: dev
    version: "1.0.0"
    demo: nodeport
spec: 
  containers:
  - name: nginx
    image: nginx