apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:  # labels are used in as selectors
    project: expense-project
    component: backend
    environment: dev  
    version: "1.0.0"
    demo: loadbalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata: 
  name: backend-loadbalancer
  labels:
    project: expense-project
    component: backend
    environment: dev
    version: "1.0.0"
    demo: loadbalancer
spec: 
  containers:
  - name: nginx
    image: nginx